/*
  Warnings:

  - The values [MANAGE_PROFILES] on the enum `Action` will be removed. If these variants are still used in the database, this will fail.
  - Added the required column `serviceType` to the `ServiceListing` table without a default value. This is not possible if the table is not empty.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Action_new" AS ENUM ('ALL', 'CREATE_ORDER', 'VIEW_SERVICES', 'WRITE_REVIEW', 'POST_SERVICE', 'MANAGE_PROFILE', 'MANAGE_TICKETS', 'MANAGE_ORDERS', 'VERIFY_COMPANY', 'APPROVE_COMPANY', 'MANAGE_COMPANY', 'APPROVE_DOCUMENTS', 'RESPOND_TO_REVIEWS', 'MANAGE_APPOINTMENTS', 'READ_USERS', 'VIEW_CLIENTS', 'VIEW_SUPPORT_TICKETS', 'MANAGE_CLIENTS', 'VIEW_ORDERS', 'MANAGE_SUBSCRIPTIONS', 'VIEW_SERVICE_LISTINGS', 'MANAGE_SUPPORT_AGENTS', 'MANAGE_DOCUMENTS', 'VIEW_APPOINTMENTS', 'MANAGE_NOTIFICATIONS', 'VIEW_NOTIFICATIONS', 'SEND_MESSAGES', 'SEND_EMAILS', 'MANAGE_MESSAGES', 'MANAGE_USERS', 'VIEW_USERS', 'VIEW_REVIEWS', 'MANAGE_REVIEWS', 'POST_REVIEW', 'APPROVE_SERVICE');
ALTER TABLE "Permission" ALTER COLUMN "action" DROP DEFAULT;
ALTER TABLE "Permission" ALTER COLUMN "action" TYPE "Action_new" USING ("action"::text::"Action_new");
ALTER TYPE "Action" RENAME TO "Action_old";
ALTER TYPE "Action_new" RENAME TO "Action";
DROP TYPE "Action_old";
ALTER TABLE "Permission" ALTER COLUMN "action" SET DEFAULT 'ALL';
COMMIT;

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "ServiceType" ADD VALUE 'COMPANY_FORMATION';
ALTER TYPE "ServiceType" ADD VALUE 'FINANCIAL_PLANNING';
ALTER TYPE "ServiceType" ADD VALUE 'MARKETING_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'CONSULTING_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'PROCUREMENT_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'MERGERS_AND_ACQUISITIONS';
ALTER TYPE "ServiceType" ADD VALUE 'IT_SUPPORT';
ALTER TYPE "ServiceType" ADD VALUE 'SOFTWARE_DEVELOPMENT';
ALTER TYPE "ServiceType" ADD VALUE 'DESIGN_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'TECH_SUPPORT';
ALTER TYPE "ServiceType" ADD VALUE 'HUMAN_RESOURCES';
ALTER TYPE "ServiceType" ADD VALUE 'RECRUITMENT';
ALTER TYPE "ServiceType" ADD VALUE 'REAL_ESTATE_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'HOME_RENOVATION';
ALTER TYPE "ServiceType" ADD VALUE 'REPAIR_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'HEALTHCARE_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'FITNESS_TRAINING';
ALTER TYPE "ServiceType" ADD VALUE 'PERSONAL_COACHING';
ALTER TYPE "ServiceType" ADD VALUE 'BEAUTY_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'LIFESTYLE_CONSULTING';
ALTER TYPE "ServiceType" ADD VALUE 'PET_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'TRAVEL_PLANNING';
ALTER TYPE "ServiceType" ADD VALUE 'EVENT_MANAGEMENT';
ALTER TYPE "ServiceType" ADD VALUE 'ENTERTAINMENT_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'FOOD_CATERING';
ALTER TYPE "ServiceType" ADD VALUE 'SECURITY_SERVICES';
ALTER TYPE "ServiceType" ADD VALUE 'LEGAL_DOCUMENT_PREPARATION';

-- AlterTable
ALTER TABLE "ServiceListing" ADD COLUMN     "serviceType" "ServiceType" NOT NULL;
