-- CreateEnum
CREATE TYPE "Action" AS ENUM ('ALL', 'CREATE_ORDER', 'VIEW_SERVICES', 'WRITE_REVIEW', 'POST_SERVICE', 'MANAGE_PROFILE', 'MANAGE_PROFILES', 'MANAGE_TICKETS', 'MANAGE_ORDERS', 'VERIFY_COMPANY', 'APPROVE_DOCUMENTS', 'RESPOND_TO_REVIEWS', 'MANAGE_APPOINTMENTS', 'READ_USERS', 'VIEW_CLIENTS');

-- AlterTable
ALTER TABLE "Permission" ADD COLUMN     "action" "Action" NOT NULL DEFAULT 'ALL',
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Role" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "RolePermission" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
